### PR TITLE
enum + set for mysql

### PR DESCRIPTION
**Pull request by 3it-lubos-nguyen**
fixes [#310 ](https://github.com/dbgate/dbgate/issues/310)

This PR adds support for enum data type in MySQL database as well as set data type.

### CODE REVIEW

**Comment by ProjectInfinity** [comment]
Seems like this needs a little bit more work to close #310. Would you be interested in also adding UI changes such as a dropdown of the options in the current enum column when editing a column of the type enum?

**Comment by 3it-lubos-nguyen** [comment]
> Seems like this needs a little bit more work to close #310. Would you be interested in also adding UI changes such as a dropdown of the options in the current enum column when editing a column of the type enum?

Sure, I'll try make the changes.

**Comment by 3it-lubos-nguyen** [comment]
> > Seems like this needs a little bit more work to close #310. Would you be interested in also adding UI changes such as a dropdown of the options in the current enum column when editing a column of the type enum?
> 
> Sure, I'll try make the changes.

Hello, I added dropdown for enum and set data types.

**Comment by 3it-lubos-nguyen** [comment]
This PR also fixes an issue [#495 ](https://github.com/dbgate/dbgate/issues/495) with generating SQL with enum and set data types.

**Comment by ProjectInfinity** [comment]
Very good. 

One thing, when I have the following column
image

should we perhaps not show the empty selection?
image

Since the column is not nullable the option should not be shown as it is an invalid option. However if the column is nullable it should set the value to null, right now it seems to be setting it to an empty string which is also not valid.

**Comment by 3it-lubos-nguyen** [comment]
The empty option (empty string) was intentional as it works in my database. I thought it is a valid option.
I've done some research and found out it works with disabled strict SQL mode. And emits an error when SQL mode is enabled = it is an invalid option.
However in the documentation they describe the empty value (empty string) as an "error value" and it causes a warning: https://mariadb.com/kb/en/enum/
So I think it will be good to completely remove the empty option.
The null value is possible to set via right click. The same option is available in any other data type columns.
Agreed?

> Very good.
> 
> One thing, when I have the following column image
> 
> should we perhaps not show the empty selection? image
> 
> Since the column is not nullable the option should not be shown as it is an invalid option. However if the column is nullable it should set the value to null, right now it seems to be setting it to an empty string which is also not valid.

**Comment by ProjectInfinity** [comment]
Yeah that sounds good. I am testing with MySQL so strict mode is default I believe.

**Comment by 3it-lubos-nguyen** [comment]
Ok, I removed the empty option for enum.

**Comment by ProjectInfinity** [comment]
Looks good to me. Thanks for your contribution.

**Pull request merged**
